

version: 2.1

jobs:
  Build:

    docker: 
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run: npm i
      - run: npm run lint
          #name: "lint code"

  test:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run: npm i
      - run: npm run test
          #name: "run test"


  analyze:

    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout
      - run: npm audit
          #name: "audit"


workflows:
  CircleCiPipeline:
    jobs:
      - Build
      - test:
          requires: 
           -  Build
      - analyze: 
          requires: 
           -  test      