

version: 2.1

jobs:
  Build:

    docker: 
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - run:
          name: "lint code"
          command: npm run lint

  test:

    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - run:
          name: "run test"
          command: npm run test        
  analyze:

    docker:
      - image: circleci/node:10.16.3

    steps:
      - checkout
      - run:
          name: "audit"
          command: npm audit



workflows:
  CircleCiPipeline:
    jobs:
      - Build
      - test:
          requires: 
           -  Build
      - analyze: 
          requires: 
           -  test      